# Generated by Django 3.2.9 on 2021-11-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plandectas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctascontable',
            name='grupo',
            field=models.CharField(choices=[('0', 'ACTIVO'), ('1', 'PASIVO'), ('2', 'PATRIMONIO'), ('3', 'RESULTADOS')], max_length=15, verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='ctascontable',
            name='subgrupo',
            field=models.CharField(choices=[('0', 'ACTIVO CORRIENTE'), ('1', 'ACTIVO NO CORRIENTE'), ('2', 'PASIVO CORRIENTE'), ('3', 'PASIVO NO CORRIENTE'), ('4', 'RESULTADOS DEL EJERCICIO')], max_length=25, verbose_name='Sub-Grupo'),
        ),
    ]
