# Generated by Django 3.2.9 on 2021-11-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plandectas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumasysaldos',
            name='codigo',
        ),
        migrations.DeleteModel(
            name='CtasContable',
        ),
        migrations.DeleteModel(
            name='SumasYSaldos',
        ),
    ]
