# Generated by Django 3.2.9 on 2021-11-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctascontable',
            name='empresa',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cliente'),
        ),
    ]
