# Generated by Django 3.2.9 on 2021-11-03 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ctascontable_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctascontable',
            name='empresa',
            field=models.CharField(max_length=50, verbose_name='Cliente'),
        ),
        migrations.CreateModel(
            name='SumasYSaldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_inicio', models.FloatField(blank=True, verbose_name='Mes de Inicio')),
                ('mes1', models.FloatField(blank=True, verbose_name='Mes 1')),
                ('mes2', models.FloatField(blank=True, verbose_name='Mes 2')),
                ('mes3', models.FloatField(blank=True, verbose_name='Mes 3')),
                ('mes4', models.FloatField(blank=True, verbose_name='Mes 4')),
                ('mes5', models.FloatField(blank=True, verbose_name='Mes 5')),
                ('mes6', models.FloatField(blank=True, verbose_name='Mes 6')),
                ('mes7', models.FloatField(blank=True, verbose_name='Mes 7')),
                ('mes8', models.FloatField(blank=True, verbose_name='Mes 8')),
                ('mes9', models.FloatField(blank=True, verbose_name='Mes 9')),
                ('mes10', models.FloatField(blank=True, verbose_name='Mes 10')),
                ('mes11', models.FloatField(blank=True, verbose_name='Mes 11')),
                ('mes12', models.FloatField(blank=True, verbose_name='Mes 12')),
                ('cierre', models.CharField(max_length=10, verbose_name='Mes de Reporte')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ctascontable')),
            ],
            options={
                'verbose_name': 'SumasYSaldos',
                'verbose_name_plural': 'SumasYSaldos',
            },
        ),
    ]
