# Generated by Django 3.2.9 on 2021-11-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211103_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctascontable',
            options={'verbose_name': 'Plan de Cuenta', 'verbose_name_plural': 'Códigos de Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='sumasysaldos',
            options={'verbose_name': 'Sumas Y Saldos', 'verbose_name_plural': 'Sumas Y Saldos'},
        ),
        migrations.AddField(
            model_name='sumasysaldos',
            name='mes13',
            field=models.FloatField(blank=True, default=0, verbose_name='Mes 13'),
        ),
    ]
