# Generated by Django 3.2.9 on 2021-11-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sumasysaldos_cierre_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumasysaldos',
            name='axi_ejercicio_anterior',
            field=models.FloatField(blank=True, default=0, verbose_name='Ajuste por Inflación Inicial'),
        ),
    ]
