# Generated by Django 3.2.9 on 2021-11-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sumasysaldos_axi_ejercicio_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumasysaldos',
            name='cierre_anterior',
            field=models.FloatField(default=0, verbose_name='Cierre Anterior'),
        ),
    ]
