# Generated by Django 3.2.9 on 2021-11-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sumasysaldos_cierre_anterior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sumasysaldos',
            name='codigo',
        ),
        migrations.DeleteModel(
            name='CtasContable',
        ),
        migrations.DeleteModel(
            name='SumasYSaldos',
        ),
    ]
